In [2]:
import torch
import matplotlib.pyplot as plt
from PIL import Image
import torch.nn.functional as F

In [13]:
def smooth_if(cond, a, b, alpha = 100):

    '''retorna a si cond > 0, sino retorna b'''
    
    sigmoid = torch.sigmoid(alpha * cond)
    return sigmoid * a + (1 - sigmoid) * b

In [14]:
x = torch.tensor(3., requires_grad = True)
y = torch.tensor(7., requires_grad = True)

In [ ]:
def smooth_max(x, y):
    return smooth_if(x-y,x,y) # <---- COMPLETAR

In [ ]:
def smooth_min(v, alpha = 100):                                    
    weights = torch.softmax( -1 * alpha * v , dim = 0) 
    return (weights * v).sum()

In [28]:
def smooth_argmin(v, alpha = 100):
    weights = torch.softmax( -1 * alpha * v , dim = 0) 
    return weights

In [26]:
v = torch.tensor([3.,-1, 0, -13], requires_grad = True)

In [27]:
smooth_min(v)

tensor([0., 0., 0., 1.], grad_fn=<SoftmaxBackward0>)


tensor(-13., grad_fn=<SumBackward0>)

In [31]:
# Smooth selection sort
def smooth_sort(u):

    size = u.size(dim=0)

    for i in range(size):
        
        min = smooth_min(u)                                                       # COMPLETAR : valor mínimo en u[i:]
        argmin = torch.cat((torch.zeros(i), smooth_argmin(u[i:]) ))                      # COMPLETAR : indice del valor mínimo en u[i:]

        # Smooth swap 

        u_temp = u.clone()  
        u_temp = u_temp - argmin * u_temp 

        u0 = u_temp[i].clone()
        u_temp[i] = min  

        u = u_temp + argmin * u0 

    return u

In [32]:
# OJO, no puede haber repetidos en s

s = torch.tensor([10,5,2,3,98,100,0], dtype = torch.float, requires_grad = True)
smooth_sort(s)

tensor([0., 0., 0., 0., 0., 0., 1.], grad_fn=<SoftmaxBackward0>)
tensor([1., 0., 0., 0., 0., 0., 0.], grad_fn=<SoftmaxBackward0>)
tensor([0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
       grad_fn=<SoftmaxBackward0>)
tensor([0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000],
       grad_fn=<SoftmaxBackward0>)
tensor([0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000],
       grad_fn=<SoftmaxBackward0>)
tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000],
       grad_fn=<SoftmaxBackward0>)
tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000],
       grad_fn=<SoftmaxBackward0>)


tensor([0., 0., 0., 0., 0., 0., 0.], grad_fn=<AddBackward0>)